# Generated by Django 3.2.7 on 2021-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
